/*
 * SPDX-FileCopyrightText: 2023-2024 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "sdkconfig.h"

/* 本地修改 #3：HID 键盘接口的总开关。
 * 用 #ifndef 包一层是为了让工程能用编译参数覆盖它，不必改这个 vendored 文件 */
#ifndef UAC_HID_KEY_ENABLE
#  ifdef CONFIG_UAC_HID_KEY
#    define UAC_HID_KEY_ENABLE  1
#  else
#    define UAC_HID_KEY_ENABLE  0
#  endif
#endif

#define SPEAK_CHANNEL_NUM    CONFIG_UAC_SPEAKER_CHANNEL_NUM  /*!< SPEAKER */
#define MIC_CHANNEL_NUM      CONFIG_UAC_MIC_CHANNEL_NUM      /*!< MIC */
#define DEFAULT_SAMPLE_RATE  CONFIG_UAC_SAMPLE_RATE          /*!< SAMPLE RATE */
#define SPK_INTERVAL_MS      CONFIG_UAC_SPK_INTERVAL_MS      /*!< READ INTERVAL in ms*/
#define MIC_INTERVAL_MS      CONFIG_UAC_MIC_INTERVAL_MS      /*!< WRITE INTERVAL in ms*/

#define IN_CTRL_CH_VALUE U32_TO_U8S_LE(AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_VOLUME_POS)

#if SPEAK_CHANNEL_NUM == 1
#define INPUT_CTRL      IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE
#elif SPEAK_CHANNEL_NUM == 2
#define INPUT_CTRL      IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE
#elif SPEAK_CHANNEL_NUM == 3
#define INPUT_CTRL      IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE
#elif SPEAK_CHANNEL_NUM == 4
#define INPUT_CTRL      IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE
#elif SPEAK_CHANNEL_NUM == 5
#define INPUT_CTRL      IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE
#elif SPEAK_CHANNEL_NUM == 6
#define INPUT_CTRL      IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE
#elif SPEAK_CHANNEL_NUM == 7
#define INPUT_CTRL      IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE
#elif SPEAK_CHANNEL_NUM == 8
#define INPUT_CTRL      IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE
#endif

#if MIC_CHANNEL_NUM == 1
#define MIC_CTRL      IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE
#elif MIC_CHANNEL_NUM == 2
#define MIC_CTRL      IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE
#elif MIC_CHANNEL_NUM == 3
#define MIC_CTRL      IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE
#elif MIC_CHANNEL_NUM == 4
#define MIC_CTRL      IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE
#elif MIC_CHANNEL_NUM == 5
#define MIC_CTRL      IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE
#elif MIC_CHANNEL_NUM == 6
#define MIC_CTRL      IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE
#elif MIC_CHANNEL_NUM == 7
#define MIC_CTRL      IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE
#elif MIC_CHANNEL_NUM == 8
#define MIC_CTRL      IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE, IN_CTRL_CH_VALUE
#endif

/* ================== 本地修改 #1 (相对 espressif/usb_device_uac 0.2.0) ==================
 *
 * 上游把麦克风的 bmChannelConfig 硬编码成 AUDIO_CHANNEL_CONFIG_FRONT_CENTER
 * (0x00000004，只有 1 个 bit)，但 bNrChannels 用的是 MIC_CHANNEL_NUM。
 * 只有 MIC_CHANNEL_NUM==1 时两者才自洽 —— 上游显然只按默认值测过。
 *
 * 设成 2 之后描述符变成「声明 2 个声道、位图只标了 1 个」，Windows 的
 * usbaudio2.sys 对这个一致性检查很严，直接 CM_PROB_FAILED_START(代码 10)，
 * 设备管理器里是一个带感叹号的「usb uac」，录音设备列表里什么都不会出现。
 *
 * 注意上游在扬声器那条路径上用的是 NON_PREDEFINED，正因为声道数可变；
 * 麦克风这条漏了。下面按声道数给出自洽的位图：
 *   1 路 -> FRONT_CENTER            保持上游默认行为
 *   2 路 -> FRONT_LEFT|FRONT_RIGHT  正经立体声，Windows 会标出 L/R
 *   其它 -> NON_PREDEFINED          位图全 0，对任意 bNrChannels 都合法
 */
#if MIC_CHANNEL_NUM == 1
#define MIC_CHANNEL_CONFIG   AUDIO_CHANNEL_CONFIG_FRONT_CENTER
#elif MIC_CHANNEL_NUM == 2
#define MIC_CHANNEL_CONFIG   (AUDIO_CHANNEL_CONFIG_FRONT_LEFT | AUDIO_CHANNEL_CONFIG_FRONT_RIGHT)
#else
#define MIC_CHANNEL_CONFIG   AUDIO_CHANNEL_CONFIG_NON_PREDEFINED
#endif

/* Feature Unit Descriptor(4.7.2.8) */
// N - Channels
#define TUD_AUDIO_DESC_SPK_FEATURE_UNIT_N_CHANNEL_LEN   (6+(SPEAK_CHANNEL_NUM+1)*4)
#define TUD_AUDIO_DESC_MIC_FEATURE_UNIT_N_CHANNEL_LEN   (6+(MIC_CHANNEL_NUM+1)*4)
#define TUD_AUDIO_DESC_FEATURE_UNIT_N_CHANNEL(_length ,_unitid, _srcid, _stridx, ...) \
  _length, TUSB_DESC_CS_INTERFACE, AUDIO_CS_AC_INTERFACE_FEATURE_UNIT, _unitid, _srcid, __VA_ARGS__, _stridx

#ifdef __cplusplus
}
#endif
